genesis:
  chain_id: "realestate"
  app_state:
    staking:
      params:
        bond_denom: "udomus"
    crisis:
      constant_fee:
        denom: udomus
    gov:
      deposit_params:
        min_deposit:
          denom: udomus

accounts:
  - name: alpha
    coins: ["3000000000udomus"]
    mnemonic: "pitch potato lady search click tumble evoke reunion artwork debris alter panda journey hand elder whisper kick oblige number plastic adult junior enlist exercise"

validator:
  name: alpha
  staked: "2000000000udomus"
client:
#  vuex:
#    path: "vue/src/store"
#  openapi:
#    path: "docs/static/openapi.yml"
faucet:
  name: alpha
  coins: ["100udomus"]